# Test
spring:
  profiles:
    active: local #local, live
    
# local Env
--- 
spring.profiles: local
spring:
  application.name : spring-security
  devtools:
    livereload:
      enabled: true # 정적 파일 실시간 갱신
    restart.enable: true
  jpa:
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    org.hibernate.type: trace #JPA 생성 쿼리 파라미터값 확인    
    
# Oracle Settings
#HikariCP Settings
#spring.datasource.hikari.*
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clonix?characterEncoding=UTF-8&serverTimezone=UTC
    username: clonix
    password: test123!@#
    connection-timeout: 6000
    maximum-pool-size: 5
server:
  servlet:
    context-path: /spring-security
  port: 8080
  error:
#    include-exception: false
    include-stacktrace: never
    path: /error
#    whitelabel:
#      enabled: false
# Eureka client
#eureka:
#  client:
#    service-url.defaultZone: ${EUREKA_URL:http://127.0.0.1:8080/eureka/}

